backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "/media"

collections:
  - name: "posts"
    label: "Блог"
    create: true
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Автор", name: "author", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}
